---
- name: Add LUN to Powermax storage array using prompts
  hosts: powermax
  gather_facts: no
  tasks:
    - name: create a new volume on Powermax and add to existing storage group
      uri:
        url: "http://{{ ansible_host }}:{{ ansible_port }}/univmax/restapi/sloprovisioning/symmetrix/{{ serial_no }}/volume"
        method: POST
        user: "{{ username }}"
        password: "{{ pwd }}"
        body_format: json
        headers:
          Content-Type: "application/json"
        body:
          {
            "volumeIdentifier": {
              "identifier_name": "{{ volname }}",
              "volumeIdentifierChoice": "identifier_name"
            },
            "capacityUnit": "{{ capunit }}",
            "cap_gb": "{{ lunsize }}",
            "volumeType": "TDEV",
            "emulation": "FBA"
          }
        force_basic_auth: yes
        status_code: 200
        validate_certs: no
      register: result

    - name: Show output
      debug:
        msg: "{{ result.json }}"
